### ISSUE TITLE
Unable to Rearrange Certain Tasks in Focus

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#213]
This seems to be a regression. #154 was fixed a while ago, but now the issue is back and much worse. I've attached a video of the issue below:

https://youtu.be/dLoPljqMTuY

Certain tasks in Focus (I haven't pinned down what causes it) are unable to be reordered no matter what. Trying to reorder other tasks around the broken task will cause the order of all the tasks in Focus view to scramble. Unpinning and re-pinning does nothing. There's just no way to get that task to the top (it's the red one in the clip).

**Comment by SamChou19815** [comment]
The issue is sometimes caused by two tasks having the same id. However, it's also possible that there is a bug in the reorder function.
https://github.com/cornell-dti/samwise/blob/65dcb9b6580f3b984a095e55828ab064b0647e9f/frontend/src/firebase/actions.ts#L222-L277
My strategy would be first isolate out the reordering code into `util/task-util.ts` and write unit tests for it to ensure we completely fix the algorithm bug (if it exists). I will also investigate whether we indeed have some duplicate id problem.

**Comment by mt-xing** [comment]
Based on the React element inspector, it doesn't look like these two tasks have the same id.

![image](https://user-images.githubusercontent.com/6147405/55099879-eba0a100-5096-11e9-9d07-30ab4b115dce.png)

**Comment by SamChou19815** [comment]
I inspected the database. It does have the same order field (`order: 43`). It's a much bigger problem because we somewhat break the invariant that no two main task can have the same order field. 
We need to perform some codebase review. However, I do believe that it's most likely be caused by a bug in task creator or a bug in the reordering function that causes the id duplication.

**Comment by SamChou19815** [comment]
The root cause has been identified. Reordering is done on a partial filtered list. During the process, it may pick an order number that is not in the partial filtered list but in somewhere else. Then it caused the duplicate id problem.
